### ISSUE TITLE
Accented spanish characters and text-transform: capitalize

### ISSUE THREAD

**Issue by dznaiko** [sorccu/cufon#252]
Hi guys!
Had an issue today with Myriad Pro Light typeface and using spanish characters with acute accent (&aacute;, &iacute;, &uacute; etc.). When cufon transforms the text of an element that has CSS rule text-transform: capitalize applied, the lowercase accented characters become the same uppercase accented characters.
I just removed the given CSS rule and it worked fine for me but you might want to take a look at this 'cause this behavior was rather unexpected from cufon.

**Comment by simonDiazSaez** [comment]
hey, i know its an old post, but i found whats going wrong with this.

search for /\b./g inside capitalize function. it have to be replaced with /(?:^|\s)./g 
:)
