### ISSUE TITLE
FontForge version on Cufon website

### ISSUE THREAD

**Issue by stickerjunkie** [sorccu/cufon#280]
Current FF on OSX just butchers things. Using the exact same settings as on the website I do not get the same result and I need to batch 100's of fonts. I read on a issue that new FF version had issues. How can I find the optimal version to use? Such as the one currently used on the cufon online generator.

**Comment by sorccu** [comment]
Sorry but there haven't been any updates for a long long time. I would recommend just using `@font-face` instead.

The server runs extremely old versions of everything. If you really MUST generate new fonts, I could perhaps take a look for you and see what the exact version is.

**Comment by stickerjunkie** [comment]
Thank you for the offer.I am using RaphaelJS so I am not sure @font-face will work as I am outputting to SVG. I presume I would lose the actual font as soon as I did so. I just went and ran a ton of fonts on the site (trying to find that right param setup). I will try this I guess. I was bummed when I spent hours writing a nice gulp script only to realize I could not get the same as the site :)

**Comment by sorccu** [comment]
Unfortunately FontForge doesn't, or at least didn't, have any tests. Newer
versions are (or were) very prone to breaking things. This project is
actually similar in that sense, it became too much of a burden trying to
keep ALL versions of ALL browsers working with manual testing.

**Comment by stickerjunkie** [comment]
I understand. Thanks for the prompt reply and thanks for the great work.
